export const WEATHER_RESPONSE = 'WEATHER_RESPONSE';
export const WEATHER_RESPONSE_FAIL = 'WEATHER_RESPONSE_FAIL';

export const SET_CITY = 'SET_CITY';

export const GEOLOCATION_RESPONSE_FAIL = 'GEOLOCATION_RESPONSE_FAIL';
export const GEOLOCATION_RESPONSE = 'GEOLOCATION_RESPONSE'